permalink: /posts/:title
markdown: kramdown

#gems:
#  - jekyll-sitemap

name: Hyuk Lee
url: #
description: #A fantastic blog that is fantastic.
twitter: #holman
facebook: https://facebook.com/yng826
